<div class="container" id="standalone">
    <div class="box">
        <h1>Terms of Service</h1>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dictum sit amet justo donec enim diam vulputate ut. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris. Mi proin sed libero enim sed faucibus turpis in. Mi quis hendrerit dolor magna eget est lorem. Adipiscing commodo elit at imperdiet dui accumsan sit. Orci a scelerisque purus semper eget duis at. Rutrum tellus pellentesque eu tincidunt tortor. Nunc aliquet bibendum enim facilisis gravida neque convallis a. Varius sit amet mattis vulputate enim nulla aliquet porttitor. In tellus integer feugiat scelerisque varius morbi enim nunc.
        <br><br>
        Libero nunc consequat interdum varius sit amet mattis vulputate. Elementum sagittis vitae et leo duis ut diam. In mollis nunc sed id semper risus in. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Mi quis hendrerit dolor magna eget est lorem ipsum. Sed arcu non odio euismod lacinia at quis risus sed. Massa tempor nec feugiat nisl pretium fusce id velit ut. A pellentesque sit amet porttitor eget dolor morbi non arcu. Id eu nisl nunc mi ipsum faucibus. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Elementum sagittis vitae et leo. Ut enim blandit volutpat maecenas volutpat blandit. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Tristique nulla aliquet enim tortor at auctor. Ornare quam viverra orci sagittis. Egestas integer eget aliquet nibh praesent tristique. Pulvinar neque laoreet suspendisse interdum consectetur libero. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Tellus mauris a diam maecenas sed enim ut sem. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh.
        <br><br>
        Nulla pellentesque dignissim enim sit amet venenatis. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Mattis enim ut tellus elementum sagittis. Posuere ac ut consequat semper. In hac habitasse platea dictumst quisque. Ipsum suspendisse ultrices gravida dictum fusce. Ut morbi tincidunt augue interdum velit. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Eget duis at tellus at urna condimentum mattis. Consectetur purus ut faucibus pulvinar elementum. Sem et tortor consequat id porta nibh venenatis. Nulla facilisi nullam vehicula ipsum a arcu.
        <br><br>
        Urna porttitor rhoncus dolor purus non enim praesent elementum facilisis. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Ornare arcu odio ut sem nulla pharetra diam sit amet. Scelerisque eleifend donec pretium vulputate sapien. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Amet tellus cras adipiscing enim eu turpis egestas. Orci dapibus ultrices in iaculis nunc sed augue lacus. Aenean euismod elementum nisi quis. Lacus suspendisse faucibus interdum posuere lorem. Augue interdum velit euismod in pellentesque massa placerat duis. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Nunc aliquet bibendum enim facilisis. Amet risus nullam eget felis eget nunc lobortis mattis. Elit ut aliquam purus sit amet luctus venenatis lectus. Faucibus nisl tincidunt eget nullam non. Tristique senectus et netus et malesuada fames.
        <br><br>
        Lorem sed risus ultricies tristique nulla aliquet enim tortor. Nisl pretium fusce id velit ut tortor pretium. Sit amet risus nullam eget felis. Est ultricies integer quis auctor elit sed vulputate mi. Sem et tortor consequat id porta nibh. Turpis tincidunt id aliquet risus feugiat in ante. Dolor sit amet consectetur adipiscing elit duis tristique. Sagittis orci a scelerisque purus semper eget duis. Faucibus purus in massa tempor nec feugiat nisl pretium. Dui vivamus arcu felis bibendum ut. Pretium vulputate sapien nec sagittis. Donec enim diam vulputate ut pharetra sit. Feugiat vivamus at augue eget arcu dictum varius duis at. Sed arcu non odio euismod lacinia at quis.
        <br><br>
        Proin nibh nisl condimentum id. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. A erat nam at lectus urna duis convallis. Lectus vestibulum mattis ullamcorper velit. Libero nunc consequat interdum varius sit amet mattis. Donec adipiscing tristique risus nec. Suspendisse sed nisi lacus sed viverra tellus in. Vitae auctor eu augue ut lectus arcu bibendum. At varius vel pharetra vel turpis nunc eget lorem dolor. Morbi enim nunc faucibus a pellentesque. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Tincidunt lobortis feugiat vivamus at. Erat imperdiet sed euismod nisi. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Et netus et malesuada fames ac. Commodo nulla facilisi nullam vehicula. Nisl nisi scelerisque eu ultrices. Posuere urna nec tincidunt praesent semper feugiat. Vitae et leo duis ut diam quam nulla porttitor.
        <br><br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dictum sit amet justo donec enim diam vulputate ut. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris. Mi proin sed libero enim sed faucibus turpis in. Mi quis hendrerit dolor magna eget est lorem. Adipiscing commodo elit at imperdiet dui accumsan sit. Orci a scelerisque purus semper eget duis at. Rutrum tellus pellentesque eu tincidunt tortor. Nunc aliquet bibendum enim facilisis gravida neque convallis a. Varius sit amet mattis vulputate enim nulla aliquet porttitor. In tellus integer feugiat scelerisque varius morbi enim nunc.
        <br><br>
        Libero nunc consequat interdum varius sit amet mattis vulputate. Elementum sagittis vitae et leo duis ut diam. In mollis nunc sed id semper risus in. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Mi quis hendrerit dolor magna eget est lorem ipsum. Sed arcu non odio euismod lacinia at quis risus sed. Massa tempor nec feugiat nisl pretium fusce id velit ut. A pellentesque sit amet porttitor eget dolor morbi non arcu. Id eu nisl nunc mi ipsum faucibus. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Elementum sagittis vitae et leo. Ut enim blandit volutpat maecenas volutpat blandit. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Tristique nulla aliquet enim tortor at auctor. Ornare quam viverra orci sagittis. Egestas integer eget aliquet nibh praesent tristique. Pulvinar neque laoreet suspendisse interdum consectetur libero. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Tellus mauris a diam maecenas sed enim ut sem. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh.
        <br><br>
        Nulla pellentesque dignissim enim sit amet venenatis. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Mattis enim ut tellus elementum sagittis. Posuere ac ut consequat semper. In hac habitasse platea dictumst quisque. Ipsum suspendisse ultrices gravida dictum fusce. Ut morbi tincidunt augue interdum velit. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Eget duis at tellus at urna condimentum mattis. Consectetur purus ut faucibus pulvinar elementum. Sem et tortor consequat id porta nibh venenatis. Nulla facilisi nullam vehicula ipsum a arcu.
        <br><br>
        Urna porttitor rhoncus dolor purus non enim praesent elementum facilisis. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Ornare arcu odio ut sem nulla pharetra diam sit amet. Scelerisque eleifend donec pretium vulputate sapien. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Amet tellus cras adipiscing enim eu turpis egestas. Orci dapibus ultrices in iaculis nunc sed augue lacus. Aenean euismod elementum nisi quis. Lacus suspendisse faucibus interdum posuere lorem. Augue interdum velit euismod in pellentesque massa placerat duis. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Nunc aliquet bibendum enim facilisis. Amet risus nullam eget felis eget nunc lobortis mattis. Elit ut aliquam purus sit amet luctus venenatis lectus. Faucibus nisl tincidunt eget nullam non. Tristique senectus et netus et malesuada fames.
        <br><br>
        Lorem sed risus ultricies tristique nulla aliquet enim tortor. Nisl pretium fusce id velit ut tortor pretium. Sit amet risus nullam eget felis. Est ultricies integer quis auctor elit sed vulputate mi. Sem et tortor consequat id porta nibh. Turpis tincidunt id aliquet risus feugiat in ante. Dolor sit amet consectetur adipiscing elit duis tristique. Sagittis orci a scelerisque purus semper eget duis. Faucibus purus in massa tempor nec feugiat nisl pretium. Dui vivamus arcu felis bibendum ut. Pretium vulputate sapien nec sagittis. Donec enim diam vulputate ut pharetra sit. Feugiat vivamus at augue eget arcu dictum varius duis at. Sed arcu non odio euismod lacinia at quis.
        <br><br>
        Proin nibh nisl condimentum id. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. A erat nam at lectus urna duis convallis. Lectus vestibulum mattis ullamcorper velit. Libero nunc consequat interdum varius sit amet mattis. Donec adipiscing tristique risus nec. Suspendisse sed nisi lacus sed viverra tellus in. Vitae auctor eu augue ut lectus arcu bibendum. At varius vel pharetra vel turpis nunc eget lorem dolor. Morbi enim nunc faucibus a pellentesque. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Tincidunt lobortis feugiat vivamus at. Erat imperdiet sed euismod nisi. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Et netus et malesuada fames ac. Commodo nulla facilisi nullam vehicula. Nisl nisi scelerisque eu ultrices. Posuere urna nec tincidunt praesent semper feugiat. Vitae et leo duis ut diam quam nulla porttitor.
        <br><br>
        This is a student project, so please don´t be rude. :)
    </div>
</div>